apiVersion: v1
kind: Namespace
metadata:
  name: spring
  labels:
    name: spring

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: spring
  name: spring
  labels:
    app: spring
spec:
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: saichler/spring:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          hostPath:
            path: /data
            type: DirectoryOrCreate
